### ISSUE TITLE
Modularize resource updater functions

### ISSUE THREAD

**Issue by yashpatel6** [uclahs-cds/pipeline-Nextflow-config#32]
We've created a few functions to provide support for custom resource updates in a few pipelines (recalibrate-BAM, call-gSNP, call-sSNV, align-RNA, etc.); a lot of them are identical so we'd like to modularize them in this repo

**Comment by nwiltsie** [comment]
@yashpatel6 is this solved by #73?

**Comment by yashpatel6** [comment]
Ah yes it should be

**Comment by yashpatel6** [comment]
Closed with #73
